name: s-tassel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  # core scientific stack
  - numpy>=1.23
  - pandas
  - scipy
  - scikit-learn
  # multi-agent & RL utils
  - pettingzoo>=1.23
  - gymnasium
  # optimal transport
  - pot  # Python Optimal Transport (binary wheels on conda-forge)
  # visualisation / dashboard
  - streamlit
  - plotly
  # ensure pip is available for any extras
  - pip